// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package model

// Injectors from wire.go:

func initializeClient() *DataClient {
	db := initDB()
	settingService := NewSettingService(db)
	textService := NewTextService(db)
	dataClient := NewDataClient(db, settingService, textService)
	return dataClient
}
